import { Sora } from 'next/font/google'
import './globals.css'

const sora = Sora({
   subsets: ['latin'],
})

export const metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
   return (
      <html lang="es">
         <body className={sora.className}>
            <main>
               {children}
            </main>
         </body>
      </html>
   )
}